CREATE DATABASE gwp;

\c gwp

CREATE USER gwp WITH PASSWORD 'gwp';

GRANT ALL PRIVILEGES ON DATABASE gwp to gwp;

GRANT ALL PRIVILEGES ON TABLE gwp to gwp;

CREATE TABLE gwp (
   ID       SERIAL PRIMARY KEY,
   CONTENT   TEXT,
  AUTHOR  VARCHAR(255)
);

GRANT USAGE, SELECT ON SEQUENCE gwp_id_seq TO gwp;

INSERT INTO gwp (content, author) VALUES
('Hello World!','Robinson Ramirez');
